@startuml
hide circle
skinparam linetype ortho
skinparam componentStyle rectangle
skinparam defaultFontSize 11

' =====================================================
' USER & PROFILE MANAGEMENT
' =====================================================

entity Users {
  *id: INT
  --
  *email: email
  *name: text
  *contactNumber: regex
  *role: enum[Admin, Manager, Coach, Members, Student, Guest]
  address: text
}

entity Media {
  *id: INT
  --
  alt: text
}

entity Members {
  *id: INT
  --
  *userId: INT <<FK>>
  profilePictureId: INT <<FK>>
  memberPaymentId: array[INT] <<FK>>
  *status: enum[active, pending, inactive]
  joinDate: date
  totalDue: number
  totalPaid: number
  achievements: array[photoId, description]
  *registrationFee: number
}

entity Students {
  *id: INT <<PK>>
  --
  *userId: INT <<FK>>
  *studentPaymentId: array[INT] <<FK>>
  profilePictureId: INT <<FK>>
  parentName: text
  parentContactNumber: regex
  joinDate: date
  skillLevel: enum
  ranking: number
  lessons_missed: array[]
  totalDue: number
  *membershipStatus: enum[active, pending, inactive]
  remarks: array[]
  achievements: array[photoId, description]
}

entity Manager {
  *id: INT <<PK>>
  --
  *userId: INT <<FK>>
  managerSalaryId: array[INT] <<FK>>
  *joinDate: date
  status: enum[active, pending, inactive]
}

entity Staffs {
  *id: INT <<PK>>
  --
  profilePictureId: INT <<FK>>
  staffSalaryId: array[INT] <<FK>>
  name: text
  contactNumber: regex
  address: text
  *joinDate: date
  status: enum[active, pending, inactive]
}

entity Coaches {
  *id: INT <<PK>>
  --
  *userId: INT <<FK>>
  coachSalaryId: array[INT] <<FK>>
  specialization: richText
  certification: array[protoId, description]
  join_date: date
  status: enum[active, pending, inactive]
}

' =====================================================
' ATTENDANCE
' =====================================================

entity CoachAttendance {
  *id: INT <<PK>>
  --
  *coachProfileId: INT <<FK>>
  *presentDate: date
}

entity StudentAttendance {
  *id: INT <<PK>>
  --
  *studentId: INT <<FK>>
  *presentDate: date
}

' =====================================================
' PACKAGES & PAYMENTS
' =====================================================

entity Packages {
  *id: INT <<PK>>
  --
  *packageName: text
  *pricePerMonth: number
  *registrationFee: number
  description: richText
}

entity MemberPayments {
  *id: INT <<PK>>
  --
  *paymentMonth: date
  *amount: number
  paymentMethod: enum[cash, mobile-banking, card]
  transactionRef: text
  *status: enum[Paid, Unpaid]
}

entity StudentPayments {
  *id: INT <<PK>>
  --
  *paymentMonth: date
  *amount: number
  paymentMethod: enum[cash, mobile-banking, card]
  transactionRef: text
  *status: enum[Due, Paid]
}

' =====================================================
' ACADEMY TRAINING
' =====================================================

entity TrainingGroup {
  *id: INT <<PK>>
  --
  *groupName: text
  *studentId: INT <<FK>>
  *coachId: INT <<FK>>
  *skillLevel: enum[beginner, intermediate, pro]
}

entity TrainingSchedule {
  *id: INT <<PK>>
  --
  *trainingGroupId: INT <<FK>>
  *coachId: INT <<FK>>
  *courtId: INT <<FK>>
  *dayOfWeek: enum
  *startTime: datetime
  *endTime: datetime
}

entity StudentProgress {
  *id: INT <<PK>>
  --
  *studentId: INT <<FK>>
  *coachId: INT <<FK>>
  *evaluationDate: date
  *evaluation: array[skillCategory, score]
  notes: string
}

' =====================================================
' COURT MANAGEMENT
' =====================================================

entity Courts {
  *Id: INT <<PK>>
  --
  *courtName: string
  description: string
}

entity CourtPricing {
  *Id: INT <<PK>>
  --
  *courtId: INT <<FK>>
  *pricingType: enum[peak, offPeak]
  *pricePerHour: number
}

entity CourtBookings {
  *Id: INT <<PK>>
  --
  *courtId: INT <<FK>>
  *userId: INT <<FK>>
  *courtPricingId: INT <<FK>>
  *bookingDate: date
  *startTime: datetime
  *endTime: datetime
  durationHours: number
  totalAmount: number
  status: enum[Due, Paid]
}

' =====================================================
' TOURNAMENT MANAGEMENT
' =====================================================

entity Tournaments {
  *id: INT <<PK>>
  --
  *tournamentName: text
  *tournamentType: enum[Academy, Members, Academy&Members, OpenForAll]
  start_date: date
  registrationEndDate: datetime
  status: enum[open, closed]
}

entity TournamentRegistrations {
  *id: INT <<PK>>
  --
  *tournamentId: INT <<FK>>
  *userId: INT <<FK>>
  registrationDate: datetime
  amount: number
  paymentDate: date
  transactionRef: text
  status: enum[Due, paid]
}

entity TournamentTeams {
  *id: INT <<PK>>
  --
  *teamName: text
  *tournamentId: INT <<FK>>
  *playerOne: INT <<FK>>
  playerTwo: INT <<FK>>
}

entity TournamentMatches {
  *id: INT <<PK>>
  --
  *tournamentId: INT <<FK>>
  *teamOneId: INT <<FK>>
  *teamTwoId: INT <<FK>>
  courtId: INT <<FK>>
  winnerId: INT <<FK>>
  scheduled_time: datetime
  teamOneScore: number
  scoreTwoScore: number
}

entity TournamentResults {
  *id: INT <<PK>>
  --
  *tournamentId: INT <<FK>>
  *teamId: INT <<FK>>
  *position: number
  prize_amount: decimal
}

' =====================================================
' EXPENDITURE
' =====================================================

entity Expenditure {
  *id: INT <<PK>>
  --
  *expenditure_type: enum[Maintenance UtilityBill, EquipmentPurchase, TournamentExpenses, IndoorFacility, Miscellaneous]
  *amount: decimal
  expenditureDate: date
  description: textarea
}

entity managerSalary {
  *id: INT <<PK>>
  --
  *paymentMonth: date
  *salary: number
  bonus: number
  *status: enum[Due, Paid]
}

entity staffSalary {
  *id: INT <<PK>>
  --
  *paymentMonth: date
  *salary: number
  bonus: number
  *status: enum[Due, Paid]
}

entity coachSalary {
  *id: INT <<PK>>
  --
  *paymentMonth: date
  *salary: number
  bonus: number
  *status: enum[Due, Paid]
}

' =====================================================
' Income
' =====================================================

entity othersIncome {
  *id: INT <<PK>>
  --
  *amount: number
  incomeDate: date
  description: textarea
}

entity Sponsorship {
  *id: INT <<PK>>
  --
  photoId: INT <<FK>>
  *sponsorName: text
  *contactNumber: regex
  amount: number
}

' =====================================================
' RELATIONSHIPS
' =====================================================

Users ||--o| Members
Users ||--o| Students
Users ||--o| Coaches
Users ||--o| Manager

Coaches ||--o| CoachAttendance
Students ||--o| StudentAttendance

Members }o--|| MemberPayments
Students }o--|| StudentPayments

TrainingGroup }o--|| Students
TrainingGroup |o--|| Coaches

TrainingSchedule |o--|| TrainingGroup
TrainingSchedule |o--|| Coaches
TrainingSchedule |o--|| Courts

StudentProgress |o--|| Students 
Coaches ||--o| StudentProgress

CourtPricing |o--|| Courts
CourtBookings |o--|| Courts
CourtBookings |o--|| Users
CourtBookings |o--|| CourtPricing

TournamentRegistrations |o--|| Users
Tournaments ||--o| TournamentRegistrations
Tournaments ||--o| TournamentTeams
Users ||--o{ TournamentTeams

Tournaments ||--o| TournamentMatches
TournamentTeams ||--o{ TournamentMatches
TournamentMatches |o--|| Courts 

Tournaments ||--o| TournamentResults 
TournamentTeams ||--o| TournamentResults 

Manager }o--|| managerSalary 
Staffs }o--|| staffSalary 
Coaches }o--|| coachSalary 

@enduml