@startuml
hide circle
skinparam linetype ortho
skinparam componentStyle rectangle
skinparam defaultFontSize 11

' =====================================================
' USER & PROFILE MANAGEMENT
' =====================================================

entity Users {
  *id: INT <<PK>>
  --
  *email: email
  *name: text
  *contactNumber: regex
  *role: enum[Admin, Manager, Coach, Members, Student, Guest]
  address: text
}

entity Media {
  *id: INT <<PK>>
  --
  alt: text
}

entity Members {
  *id: INT <<PK>>
  --
  *userId: INT <<FK>>
  profilePictureId: INT <<FK>>
  *status: enum[active, pending, inactive]
  joinDate: date
  totalDue: number
  totalPaid: number
  achievements: array[photoId, description]
}

entity Students {
  *id: INT <<PK>>
  --
  *userId: INT <<FK>>
  profilePictureId: INT <<FK>>
  parentName: text
  parentContactNumber: regex
  joinDate: date
  skillLevel: enum
  ranking: number
  *membershipStatus: enum[active, pending, inactive]
  achievements: array[photoId, description]
}

entity Manager {
  *id: INT <<PK>>
  --
  *userId: INT <<FK>>
  managerSalaryId: array[INT] <<FK>>
  *joinDate: date
  status: enum[active, pending, inactive]
}

entity Staffs {
  *id: INT <<PK>>
  --
  profilePictureId: INT <<FK>>
  staffSalaryId: array[INT] <<FK>>
  name: text
  contactNumber: regex
  address: text
  *joinDate: date
  status: enum[active, pending, inactive]
}

entity Coaches {
  *id: INT <<PK>>
  --
  *userId: INT <<FK>>
  coachSalaryId: array[INT] <<FK>>
  specialization: richText
  certification: array[protoId, description]
  join_date: date
  status: enum[active, pending, inactive]
}

' =====================================================
' ATTENDANCE
' =====================================================

entity StudentAttendance {
  *id: INT <<PK>>
  --
  *studentId: INT <<FK>>
  *attendances: array[Month, Notes, AbsentDays[type, date]]
}

' =====================================================
' PACKAGES & PAYMENTS
' =====================================================

entity Packages {
  *id: INT <<PK>>
  --
  *packageName: text
  *pricePerMonth: number
  *registrationFee: number
  description: richText
}

entity MemberPayments {
  *id: INT <<PK>>
  --
  *memberId: INT <<FK>>
  *registrationFee: number
  *paymentMonth: date
  *amount: number
  paymentMethod: enum[cash, mobile-banking, card]
  transactionRef: text
  *status: enum[Paid, Unpaid]
}

entity StudentPayments {
  *id: INT <<PK>>
  --
  *studentId: INT <<FK>>
  *registrationFee: number
  *paymentMonth: date
  *amount: number
  paymentMethod: enum[cash, mobile-banking, card]
  transactionRef: text
  *status: enum[Due, Paid]
}

entity BookingPayments {
  *id: INT <<PK>>
  --
  *bookingId: INT <<FK>>
  *totalAmount: number
  *paymentStatus: enum[Paid, Unpaid]
}

' =====================================================
' ACADEMY TRAINING
' =====================================================

entity TrainingGroup {
  *id: INT <<PK>>
  --
  *groupName: text
  *studentId: INT <<FK>>
  *coachId: INT <<FK>>
  *skillLevel: enum[beginner, intermediate, pro]
}

entity TrainingSchedules {
  *id: INT <<PK>>
  --
  *trainingGroupId: INT <<FK>>
  *coachId: INT <<FK>>
  *courtId: INT <<FK>>
  *dayOfWeek: enum
  *startTime: datetime
  *endTime: datetime
}

entity MembersSchedules {
  *id: INT <<PK>>
  --
  *courtId: INT <<FK>>
  *dayOfWeek: enum
  *startTime: datetime
  *endTime: datetime
}

entity StudentProgress {
  *id: INT <<PK>>
  --
  *studentId: INT <<FK>>
  *coachId: INT <<FK>>
  *evaluation: array[skillCategory, score, remarks]
}

' =====================================================
' COURT MANAGEMENT
' =====================================================

entity Courts {
  *Id: INT <<PK>>
  --
  *courtName: string
  peakHorPrice: number
  normalHorPrice: number
}

entity CourtBookings {
  *Id: INT <<PK>>
  --
  *courtId: INT <<FK>>
  *userId: INT <<FK>>
  *bookingDate: date
  *startTime: datetime
  *endTime: datetime
}

' =====================================================
' TOURNAMENT MANAGEMENT
' =====================================================

entity Tournaments {
  *id: INT <<PK>>
  --
  *tournamentName: text
  *registrationFee: number
  *tournamentType: enum[Academy, Members, Academy&Members, OpenForAll]
  registrationStartDate: date
  registrationEndDate: date
  status: enum[open, closed]
}

entity TournamentRegistrations {
  *id: INT <<PK>>
  --
  *tournamentId: INT <<FK>>
  *userId: INT <<FK>>
  registrationDate: datetime
  paymentDate: date
  status: enum[Due, paid]
}

entity TournamentTeams {
  *id: INT <<PK>>
  --
  *teamName: text
  *tournamentId: INT <<FK>>
  *playerOne: INT <<FK>>
  playerTwo: INT <<FK>>
}

entity TournamentMatches {
  *id: INT <<PK>>
  --
  *tournamentId: INT <<FK>>
  *teamOneId: INT <<FK>>
  *teamTwoId: INT <<FK>>
  courtId: INT <<FK>>
  winnerId: INT <<FK>>
  scheduled_time: datetime
  teamOneScore: number
  scoreTwoScore: number
}

entity TournamentResults {
  *id: INT <<PK>>
  --
  *tournamentId: INT <<FK>>
  *teamId: INT <<FK>>
  *position: number
  prize_amount: decimal
}

' =====================================================
' EXPENDITURE
' =====================================================

entity Expenditure {
  *id: INT <<PK>>
  --
  *expenditure_type: enum[Salaries ...]
' Maintenance, UtilityBill, EquipmentPurchase, TournamentExpenses, IndoorFacility, Miscellaneous
  *amount: decimal
  expenditureDate: date
  description: textarea
}

entity ManagerSalary {
  *id: INT <<PK>>
  --
  *paymentMonth: date
  *salary: number
  bonus: number
  *status: enum[Due, Paid]
}

entity StaffSalary {
  *id: INT <<PK>>
  --
  *paymentMonth: date
  *salary: number
  bonus: number
  *status: enum[Due, Paid]
}

entity CoachSalary {
  *id: INT <<PK>>
  --
  *paymentMonth: date
  *salary: number
  bonus: number
  *status: enum[Due, Paid]
}

' =====================================================
' Income
' =====================================================

entity Income {
  *id: INT <<PK>>
  --
  *amount: number
  *income_type: enum[MembershipFee ...] 
' MembershipFee, RegistrationFee, TournamentFee, Other
  incomeDate: date
  description: textarea
}

entity Sponsors {
  *id: INT <<PK>>
  --
  photoId: INT <<FK>>
  *sponsorName: text
  *contactNumber: regex
  amounts: array[amount, date]
}

' =====================================================
' RELATIONSHIPS
' =====================================================

Users ||--o| Members
Users ||--o| Students
Users ||--o| Coaches
Users ||--o| Manager

Packages ||--o| Members
Packages ||--o| Students

Students ||--o| StudentAttendance

Members ||--o{ MemberPayments
Students ||--o{ StudentPayments

TrainingGroup }o--|| Students
TrainingGroup |o--|| Coaches

TrainingSchedules |o--|| TrainingGroup
TrainingSchedules |o--|| Coaches
TrainingSchedules |o--|| Courts

MembersSchedules |o--|| Courts

StudentProgress |o--|| Students 
Coaches ||--o| StudentProgress

CourtBookings |o--|| Courts
CourtBookings |o--|| Users
BookingPayments |o--|| CourtBookings

TournamentRegistrations |o--|| Users
Tournaments ||--o| TournamentRegistrations
Tournaments ||--o| TournamentTeams
Users ||--o{ TournamentTeams

Tournaments ||--o| TournamentMatches
TournamentTeams ||--o{ TournamentMatches
TournamentMatches |o--|| Courts 

Tournaments ||--o| TournamentResults 
TournamentTeams ||--o| TournamentResults 

Manager ||--o{ ManagerSalary 
Staffs ||--o{ StaffSalary 
Coaches ||--o{ CoachSalary

Expenditure ||--o| ManagerSalary
Expenditure ||--o| StaffSalary
Expenditure ||--o| CoachSalary

Income ||--o| MemberPayments
Income ||--o| StudentPayments
Income ||--o| TournamentRegistrations
Income ||--o| Sponsors

Media ||--o| Members
Media ||--o| Students
Media ||--o| Coaches
Media ||--o| Manager
Media ||--o| Sponsors

@enduml