/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    tenants: Tenant;
    'subscription-invoices': SubscriptionInvoice;
    'subscription-events': SubscriptionEvent;
    users: User;
    media: Media;
    courts: Court;
    packages: Package;
    students: Student;
    members: Member;
    coaches: Coach;
    'coach-salaries': CoachSalary;
    managers: Manager;
    staffs: Staff;
    expenditures: Expenditure;
    'member-payments': MemberPayment;
    'student-payments': StudentPayment;
    'booking-payments': BookingPayment;
    payments: Payment;
    sponsors: Sponsor;
    'other-incomes': OtherIncome;
    'training-groups': TrainingGroup;
    'student-attendance': StudentAttendance;
    'student-progress': StudentProgress;
    tournaments: Tournament;
    'tournament-registrations': TournamentRegistration;
    'tournament-teams': TournamentTeam;
    'tournament-matches': TournamentMatch;
    'tournament-results': TournamentResult;
    'training-schedules': TrainingSchedule;
    'member-schedules': MemberSchedule;
    'court-bookings': CourtBooking;
    notifications: Notification;
    'audit-logs': AuditLog;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    'subscription-invoices': SubscriptionInvoicesSelect<false> | SubscriptionInvoicesSelect<true>;
    'subscription-events': SubscriptionEventsSelect<false> | SubscriptionEventsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    courts: CourtsSelect<false> | CourtsSelect<true>;
    packages: PackagesSelect<false> | PackagesSelect<true>;
    students: StudentsSelect<false> | StudentsSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    coaches: CoachesSelect<false> | CoachesSelect<true>;
    'coach-salaries': CoachSalariesSelect<false> | CoachSalariesSelect<true>;
    managers: ManagersSelect<false> | ManagersSelect<true>;
    staffs: StaffsSelect<false> | StaffsSelect<true>;
    expenditures: ExpendituresSelect<false> | ExpendituresSelect<true>;
    'member-payments': MemberPaymentsSelect<false> | MemberPaymentsSelect<true>;
    'student-payments': StudentPaymentsSelect<false> | StudentPaymentsSelect<true>;
    'booking-payments': BookingPaymentsSelect<false> | BookingPaymentsSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    sponsors: SponsorsSelect<false> | SponsorsSelect<true>;
    'other-incomes': OtherIncomesSelect<false> | OtherIncomesSelect<true>;
    'training-groups': TrainingGroupsSelect<false> | TrainingGroupsSelect<true>;
    'student-attendance': StudentAttendanceSelect<false> | StudentAttendanceSelect<true>;
    'student-progress': StudentProgressSelect<false> | StudentProgressSelect<true>;
    tournaments: TournamentsSelect<false> | TournamentsSelect<true>;
    'tournament-registrations': TournamentRegistrationsSelect<false> | TournamentRegistrationsSelect<true>;
    'tournament-teams': TournamentTeamsSelect<false> | TournamentTeamsSelect<true>;
    'tournament-matches': TournamentMatchesSelect<false> | TournamentMatchesSelect<true>;
    'tournament-results': TournamentResultsSelect<false> | TournamentResultsSelect<true>;
    'training-schedules': TrainingSchedulesSelect<false> | TrainingSchedulesSelect<true>;
    'member-schedules': MemberSchedulesSelect<false> | MemberSchedulesSelect<true>;
    'court-bookings': CourtBookingsSelect<false> | CourtBookingsSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      enforceTenantSubscriptions: TaskEnforceTenantSubscriptions;
      sendBillingReminders: TaskSendBillingReminders;
      dispatchPendingNotifications: TaskDispatchPendingNotifications;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  slug: string;
  contactNumber?: string | null;
  address?: string | null;
  isActive: boolean;
  settings: {
    trialDurationDaysDefault: number;
    billingReminderDaysBefore: number;
    readOnlyOnSuspended: boolean;
    cancellationPolicy?: string | null;
  };
  subscriptionPlan: {
    billingType: 'recurring' | 'one-time';
    monthlyPrice?: number | null;
    oneTimePrice?: number | null;
    currency: string;
    setupFee?: number | null;
    features?: {
      maxCourts?: number | null;
      maxUsers?: number | null;
      tournamentsEnabled?: boolean | null;
      whatsappNotificationsEnabled?: boolean | null;
      reportsEnabled?: boolean | null;
    };
  };
  subscriptionStatus: 'trialing' | 'active' | 'past_due' | 'suspended' | 'cancelled';
  /**
   * Calculated automatically from the selected plan.
   */
  billingCycle: 'monthly' | 'one-time';
  trialStartedAt?: string | null;
  trialEndsAt?: string | null;
  currentPeriodStart?: string | null;
  currentPeriodEnd?: string | null;
  nextBillingDate?: string | null;
  gracePeriodDays?: number | null;
  autoSuspendOnExpiry: boolean;
  /**
   * Stamped when a one-time (lifetime) invoice is paid.
   */
  lifetimePurchasedAt?: string | null;
  /**
   * Stamped once the plan’s setup fee has been invoiced and paid.
   */
  setupFeeChargedAt?: string | null;
  suspendedAt?: string | null;
  suspendedReason?: string | null;
  cancelledAt?: string | null;
  cancelledReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscription-invoices".
 */
export interface SubscriptionInvoice {
  id: number;
  tenant: number | Tenant;
  planSnapshot: {
    billingType: 'recurring' | 'one-time';
    monthlyPrice?: number | null;
    oneTimePrice?: number | null;
    currency: string;
    setupFee?: number | null;
  };
  /**
   * One-time invoices have no billing period and activate the tenant permanently once paid.
   */
  invoiceType: 'subscription' | 'one-time';
  /**
   * When present, the invoice amount is the sum of these lines.
   */
  lineItems?:
    | {
        label: string;
        kind: 'subscription' | 'one-time' | 'setup-fee';
        amount: number;
        id?: string | null;
      }[]
    | null;
  billingPeriodStart?: string | null;
  billingPeriodEnd?: string | null;
  dueAt: string;
  /**
   * Recalculated from the line items when any are present.
   */
  amount: number;
  currency: string;
  status: 'draft' | 'pending' | 'paid' | 'failed' | 'void';
  paymentMethod?: ('bkash' | 'nagad' | 'sslcommerz' | 'manual/bank-transfer') | null;
  gatewayTransactionId?: string | null;
  issuedAt: string;
  paidAt?: string | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  contactNumber?: string | null;
  role: 'super-admin' | 'admin' | 'manager' | 'coach' | 'staff' | 'member' | 'student' | 'guest';
  isSuperAdmin?: boolean | null;
  tenantSubscriptionStatus?: string | null;
  address?: string | null;
  tenants?:
    | {
        tenant: number | Tenant;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscription-events".
 */
export interface SubscriptionEvent {
  id: number;
  tenant: number | Tenant;
  eventType:
    | 'trial_started'
    | 'trial_extended'
    | 'trial_converted'
    | 'plan_changed'
    | 'one_time_purchased'
    | 'setup_fee_charged'
    | 'invoice_generated'
    | 'payment_received'
    | 'payment_failed'
    | 'suspended'
    | 'reactivated'
    | 'cancelled';
  fromValue?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  toValue?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  triggeredBy?: (number | null) | User;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courts".
 */
export interface Court {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  peakHourPrice: number;
  normalHourPrice: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages".
 */
export interface Package {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  price: number;
  registrationFee: number;
  features?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "students".
 */
export interface Student {
  id: number;
  tenant?: (number | null) | Tenant;
  studentName?: string | null;
  user: number | User;
  joinDate: string;
  status: 'active' | 'pending' | 'inactive';
  profilePicture?: (number | null) | Media;
  parentName?: string | null;
  parentContactNumber?: string | null;
  skillLevel?: ('beginner' | 'intermediate' | 'advanced') | null;
  ranking?: number | null;
  achievements?:
    | {
        title: string;
        description?: string | null;
        date?: string | null;
        picture?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  tenant?: (number | null) | Tenant;
  memberName?: string | null;
  user: number | User;
  joinDate: string;
  status: 'active' | 'pending' | 'inactive';
  profilePicture?: (number | null) | Media;
  achievements?:
    | {
        title: string;
        description?: string | null;
        date?: string | null;
        picture?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coaches".
 */
export interface Coach {
  id: number;
  tenant?: (number | null) | Tenant;
  coachName?: string | null;
  user: number | User;
  joinDate: string;
  status: 'active' | 'pending' | 'inactive';
  profilePicture?: (number | null) | Media;
  specialization?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  certifications?:
    | {
        title: string;
        description?: string | null;
        date?: string | null;
        picture?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  achievements?:
    | {
        title: string;
        description?: string | null;
        date?: string | null;
        picture?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coach-salaries".
 */
export interface CoachSalary {
  id: number;
  tenant?: (number | null) | Tenant;
  coach: number | Coach;
  totalDue?: number | null;
  totalPaid?: number | null;
  salaries?:
    | {
        paymentMonth?: string | null;
        salary: number;
        status: 'paid' | 'unpaid';
        paymentMethod: 'cash' | 'mobile-banking' | 'card';
        transactionRef?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "managers".
 */
export interface Manager {
  id: number;
  tenant?: (number | null) | Tenant;
  user: number | User;
  totalDue?: number | null;
  totalPaid?: number | null;
  profilePicture?: (number | null) | Media;
  joinDate: string;
  status: 'active' | 'pending' | 'inactive';
  salaries?:
    | {
        paymentMonth?: string | null;
        salary: number;
        status: 'paid' | 'unpaid';
        paymentMethod: 'cash' | 'mobile-banking' | 'card';
        transactionRef?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staffs".
 */
export interface Staff {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  totalDue?: number | null;
  totalPaid?: number | null;
  profilePicture?: (number | null) | Media;
  contactNumber: string;
  address?: string | null;
  joinDate: string;
  status: 'active' | 'pending' | 'inactive';
  salaries?:
    | {
        paymentMonth?: string | null;
        salary: number;
        status: 'paid' | 'unpaid';
        paymentMethod: 'cash' | 'mobile-banking' | 'card';
        transactionRef?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expenditures".
 */
export interface Expenditure {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  description?: string | null;
  type:
    | 'maintenance'
    | 'utility-bill'
    | 'equipment-purchase'
    | 'tournament-expenses'
    | 'indoor-facility'
    | 'miscellaneous';
  amount: number;
  date: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "member-payments".
 */
export interface MemberPayment {
  id: number;
  tenant?: (number | null) | Tenant;
  user: number | Member;
  totalDue?: number | null;
  totalPaid?: number | null;
  registrationFee: number;
  registrationDate: string;
  payments?:
    | {
        paymentMonth?: string | null;
        amount: number;
        status: 'paid' | 'unpaid';
        paymentMethod: 'cash' | 'mobile-banking' | 'card';
        transactionRef?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "student-payments".
 */
export interface StudentPayment {
  id: number;
  tenant?: (number | null) | Tenant;
  student: number | Student;
  totalDue?: number | null;
  totalPaid?: number | null;
  registrationFee: number;
  registrationDate: string;
  payments?:
    | {
        paymentMonth?: string | null;
        amount: number;
        status: 'paid' | 'unpaid';
        paymentMethod: 'cash' | 'mobile-banking' | 'card';
        transactionRef?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "booking-payments".
 */
export interface BookingPayment {
  id: number;
  tenant?: (number | null) | Tenant;
  booking: number | CourtBooking;
  totalAmount: number;
  paymentStatus: 'paid' | 'unpaid';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "court-bookings".
 */
export interface CourtBooking {
  id: number;
  tenant?: (number | null) | Tenant;
  title?: string | null;
  user: number | User;
  bookings: {
    courts: (number | Court)[];
    bookingDate: string;
    startTime: string;
    endTime: string;
    id?: string | null;
  }[];
  confirmed?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: number;
  tenant?: (number | null) | Tenant;
  payerType: 'member' | 'student' | 'guest';
  payer?:
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'students';
        value: number | Student;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  context: 'membership' | 'registration-fee' | 'court-booking' | 'tournament-fee';
  contextRefId?: string | null;
  amount: number;
  paymentMethod: 'cash' | 'bkash' | 'nagad' | 'sslcommerz' | 'card';
  status: 'pending' | 'paid' | 'failed' | 'refunded' | 'due';
  gatewayTransactionId?: string | null;
  gatewayStatus?: string | null;
  invoiceNumber?: string | null;
  dueDate?: string | null;
  paidAt?: string | null;
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors".
 */
export interface Sponsor {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  contactNumber: string;
  description?: string | null;
  picture?: (number | null) | Media;
  amounts?:
    | {
        amount: number;
        date: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "other-incomes".
 */
export interface OtherIncome {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  amount: number;
  date: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "training-groups".
 */
export interface TrainingGroup {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  students: (number | Student)[];
  coach: number | Coach;
  skillLevel: 'beginner' | 'intermediate' | 'advanced';
  status: 'active' | 'pending' | 'inactive';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "student-attendance".
 */
export interface StudentAttendance {
  id: number;
  tenant?: (number | null) | Tenant;
  student: number | Student;
  attendances?:
    | {
        attendanceMonth?: string | null;
        absentDates?:
          | {
              type?: ('single' | 'range') | null;
              date?: string | null;
              from?: string | null;
              to?: string | null;
              reason?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "student-progress".
 */
export interface StudentProgress {
  id: number;
  tenant?: (number | null) | Tenant;
  student: number | Student;
  coach: number | Coach;
  evaluations?:
    | {
        evaluationMonth?: string | null;
        remarks?: string | null;
        evaluation?:
          | {
              skillCategory?:
                | (
                    | 'forehand'
                    | 'backhand'
                    | 'serve'
                    | 'smash'
                    | 'dropShot'
                    | 'netPlay'
                    | 'footwork'
                    | 'stamina'
                    | 'technique'
                    | 'strategy'
                  )
                | null;
              score?: number | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tournaments".
 */
export interface Tournament {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  tournamentType: 'academy' | 'members' | 'academy&members' | 'openForAll';
  registrationFee: number;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  registrationStartDate: string;
  registrationEndDate: string;
  status: 'open' | 'closed';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tournament-registrations".
 */
export interface TournamentRegistration {
  id: number;
  tenant?: (number | null) | Tenant;
  tournament: number | Tournament;
  user: number | User;
  registrationDate?: string | null;
  paymentStatus?: ('paid' | 'unpaid') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tournament-teams".
 */
export interface TournamentTeam {
  id: number;
  tenant?: (number | null) | Tenant;
  tournament: number | Tournament;
  teams?:
    | {
        teamName: string;
        players: (number | User)[];
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tournament-matches".
 */
export interface TournamentMatch {
  id: number;
  tenant?: (number | null) | Tenant;
  tournament: number | Tournament;
  matches?:
    | {
        teamOne: string;
        teamTwo: string;
        winner?: string | null;
        court: number | Court;
        scheduledTime: string;
        scores?:
          | {
              teamOneScore?: number | null;
              teamTwoScore?: number | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tournament-results".
 */
export interface TournamentResult {
  id: number;
  tenant?: (number | null) | Tenant;
  tournament: number | Tournament;
  teamPositions: {
    team: string;
    position: number;
    prizeAmount: number;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "training-schedules".
 */
export interface TrainingSchedule {
  id: number;
  tenant?: (number | null) | Tenant;
  trainingGroup: number | TrainingGroup;
  coach: number | Coach;
  schedules?:
    | {
        courts: (number | Court)[];
        daysOfWeek: ('saturday' | 'sunday' | 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday')[];
        startTime: string;
        endTime: string;
        id?: string | null;
      }[]
    | null;
  offDays?:
    | {
        type?: ('single' | 'range') | null;
        date?: string | null;
        from?: string | null;
        to?: string | null;
        reason: string;
        id?: string | null;
      }[]
    | null;
  status: 'active' | 'inactive';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "member-schedules".
 */
export interface MemberSchedule {
  id: number;
  tenant?: (number | null) | Tenant;
  shiftName: string;
  schedules?:
    | {
        courts: (number | Court)[];
        daysOfWeek: ('saturday' | 'sunday' | 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday')[];
        startTime: string;
        endTime: string;
        id?: string | null;
      }[]
    | null;
  offDays?:
    | {
        type?: ('single' | 'range') | null;
        date?: string | null;
        from?: string | null;
        to?: string | null;
        reason: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  tenant?: (number | null) | Tenant;
  userId?: (number | null) | User;
  channel: 'whatsapp' | 'email' | 'in-app';
  type: string;
  status: 'pending' | 'queued' | 'sent' | 'failed';
  payload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  sentAt?: string | null;
  /**
   * Set when the recipient opens the notification from the header bell.
   */
  readAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  tenant?: (number | null) | Tenant;
  userId?: (number | null) | User;
  action: string;
  collection: string;
  documentId: string;
  diff?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  ip?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'enforceTenantSubscriptions' | 'sendBillingReminders' | 'dispatchPendingNotifications';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'enforceTenantSubscriptions' | 'sendBillingReminders' | 'dispatchPendingNotifications') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'subscription-invoices';
        value: number | SubscriptionInvoice;
      } | null)
    | ({
        relationTo: 'subscription-events';
        value: number | SubscriptionEvent;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'courts';
        value: number | Court;
      } | null)
    | ({
        relationTo: 'packages';
        value: number | Package;
      } | null)
    | ({
        relationTo: 'students';
        value: number | Student;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'coaches';
        value: number | Coach;
      } | null)
    | ({
        relationTo: 'coach-salaries';
        value: number | CoachSalary;
      } | null)
    | ({
        relationTo: 'managers';
        value: number | Manager;
      } | null)
    | ({
        relationTo: 'staffs';
        value: number | Staff;
      } | null)
    | ({
        relationTo: 'expenditures';
        value: number | Expenditure;
      } | null)
    | ({
        relationTo: 'member-payments';
        value: number | MemberPayment;
      } | null)
    | ({
        relationTo: 'student-payments';
        value: number | StudentPayment;
      } | null)
    | ({
        relationTo: 'booking-payments';
        value: number | BookingPayment;
      } | null)
    | ({
        relationTo: 'payments';
        value: number | Payment;
      } | null)
    | ({
        relationTo: 'sponsors';
        value: number | Sponsor;
      } | null)
    | ({
        relationTo: 'other-incomes';
        value: number | OtherIncome;
      } | null)
    | ({
        relationTo: 'training-groups';
        value: number | TrainingGroup;
      } | null)
    | ({
        relationTo: 'student-attendance';
        value: number | StudentAttendance;
      } | null)
    | ({
        relationTo: 'student-progress';
        value: number | StudentProgress;
      } | null)
    | ({
        relationTo: 'tournaments';
        value: number | Tournament;
      } | null)
    | ({
        relationTo: 'tournament-registrations';
        value: number | TournamentRegistration;
      } | null)
    | ({
        relationTo: 'tournament-teams';
        value: number | TournamentTeam;
      } | null)
    | ({
        relationTo: 'tournament-matches';
        value: number | TournamentMatch;
      } | null)
    | ({
        relationTo: 'tournament-results';
        value: number | TournamentResult;
      } | null)
    | ({
        relationTo: 'training-schedules';
        value: number | TrainingSchedule;
      } | null)
    | ({
        relationTo: 'member-schedules';
        value: number | MemberSchedule;
      } | null)
    | ({
        relationTo: 'court-bookings';
        value: number | CourtBooking;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  contactNumber?: T;
  address?: T;
  isActive?: T;
  settings?:
    | T
    | {
        trialDurationDaysDefault?: T;
        billingReminderDaysBefore?: T;
        readOnlyOnSuspended?: T;
        cancellationPolicy?: T;
      };
  subscriptionPlan?:
    | T
    | {
        billingType?: T;
        monthlyPrice?: T;
        oneTimePrice?: T;
        currency?: T;
        setupFee?: T;
        features?:
          | T
          | {
              maxCourts?: T;
              maxUsers?: T;
              tournamentsEnabled?: T;
              whatsappNotificationsEnabled?: T;
              reportsEnabled?: T;
            };
      };
  subscriptionStatus?: T;
  billingCycle?: T;
  trialStartedAt?: T;
  trialEndsAt?: T;
  currentPeriodStart?: T;
  currentPeriodEnd?: T;
  nextBillingDate?: T;
  gracePeriodDays?: T;
  autoSuspendOnExpiry?: T;
  lifetimePurchasedAt?: T;
  setupFeeChargedAt?: T;
  suspendedAt?: T;
  suspendedReason?: T;
  cancelledAt?: T;
  cancelledReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscription-invoices_select".
 */
export interface SubscriptionInvoicesSelect<T extends boolean = true> {
  tenant?: T;
  planSnapshot?:
    | T
    | {
        billingType?: T;
        monthlyPrice?: T;
        oneTimePrice?: T;
        currency?: T;
        setupFee?: T;
      };
  invoiceType?: T;
  lineItems?:
    | T
    | {
        label?: T;
        kind?: T;
        amount?: T;
        id?: T;
      };
  billingPeriodStart?: T;
  billingPeriodEnd?: T;
  dueAt?: T;
  amount?: T;
  currency?: T;
  status?: T;
  paymentMethod?: T;
  gatewayTransactionId?: T;
  issuedAt?: T;
  paidAt?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscription-events_select".
 */
export interface SubscriptionEventsSelect<T extends boolean = true> {
  tenant?: T;
  eventType?: T;
  fromValue?: T;
  toValue?: T;
  triggeredBy?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  contactNumber?: T;
  role?: T;
  isSuperAdmin?: T;
  tenantSubscriptionStatus?: T;
  address?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courts_select".
 */
export interface CourtsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  peakHourPrice?: T;
  normalHourPrice?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages_select".
 */
export interface PackagesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  price?: T;
  registrationFee?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "students_select".
 */
export interface StudentsSelect<T extends boolean = true> {
  tenant?: T;
  studentName?: T;
  user?: T;
  joinDate?: T;
  status?: T;
  profilePicture?: T;
  parentName?: T;
  parentContactNumber?: T;
  skillLevel?: T;
  ranking?: T;
  achievements?:
    | T
    | {
        title?: T;
        description?: T;
        date?: T;
        picture?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  tenant?: T;
  memberName?: T;
  user?: T;
  joinDate?: T;
  status?: T;
  profilePicture?: T;
  achievements?:
    | T
    | {
        title?: T;
        description?: T;
        date?: T;
        picture?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coaches_select".
 */
export interface CoachesSelect<T extends boolean = true> {
  tenant?: T;
  coachName?: T;
  user?: T;
  joinDate?: T;
  status?: T;
  profilePicture?: T;
  specialization?: T;
  certifications?:
    | T
    | {
        title?: T;
        description?: T;
        date?: T;
        picture?: T;
        id?: T;
      };
  achievements?:
    | T
    | {
        title?: T;
        description?: T;
        date?: T;
        picture?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coach-salaries_select".
 */
export interface CoachSalariesSelect<T extends boolean = true> {
  tenant?: T;
  coach?: T;
  totalDue?: T;
  totalPaid?: T;
  salaries?:
    | T
    | {
        paymentMonth?: T;
        salary?: T;
        status?: T;
        paymentMethod?: T;
        transactionRef?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "managers_select".
 */
export interface ManagersSelect<T extends boolean = true> {
  tenant?: T;
  user?: T;
  totalDue?: T;
  totalPaid?: T;
  profilePicture?: T;
  joinDate?: T;
  status?: T;
  salaries?:
    | T
    | {
        paymentMonth?: T;
        salary?: T;
        status?: T;
        paymentMethod?: T;
        transactionRef?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staffs_select".
 */
export interface StaffsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  totalDue?: T;
  totalPaid?: T;
  profilePicture?: T;
  contactNumber?: T;
  address?: T;
  joinDate?: T;
  status?: T;
  salaries?:
    | T
    | {
        paymentMonth?: T;
        salary?: T;
        status?: T;
        paymentMethod?: T;
        transactionRef?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expenditures_select".
 */
export interface ExpendituresSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  description?: T;
  type?: T;
  amount?: T;
  date?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "member-payments_select".
 */
export interface MemberPaymentsSelect<T extends boolean = true> {
  tenant?: T;
  user?: T;
  totalDue?: T;
  totalPaid?: T;
  registrationFee?: T;
  registrationDate?: T;
  payments?:
    | T
    | {
        paymentMonth?: T;
        amount?: T;
        status?: T;
        paymentMethod?: T;
        transactionRef?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "student-payments_select".
 */
export interface StudentPaymentsSelect<T extends boolean = true> {
  tenant?: T;
  student?: T;
  totalDue?: T;
  totalPaid?: T;
  registrationFee?: T;
  registrationDate?: T;
  payments?:
    | T
    | {
        paymentMonth?: T;
        amount?: T;
        status?: T;
        paymentMethod?: T;
        transactionRef?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "booking-payments_select".
 */
export interface BookingPaymentsSelect<T extends boolean = true> {
  tenant?: T;
  booking?: T;
  totalAmount?: T;
  paymentStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  tenant?: T;
  payerType?: T;
  payer?: T;
  context?: T;
  contextRefId?: T;
  amount?: T;
  paymentMethod?: T;
  status?: T;
  gatewayTransactionId?: T;
  gatewayStatus?: T;
  invoiceNumber?: T;
  dueDate?: T;
  paidAt?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors_select".
 */
export interface SponsorsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  contactNumber?: T;
  description?: T;
  picture?: T;
  amounts?:
    | T
    | {
        amount?: T;
        date?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "other-incomes_select".
 */
export interface OtherIncomesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  amount?: T;
  date?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "training-groups_select".
 */
export interface TrainingGroupsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  students?: T;
  coach?: T;
  skillLevel?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "student-attendance_select".
 */
export interface StudentAttendanceSelect<T extends boolean = true> {
  tenant?: T;
  student?: T;
  attendances?:
    | T
    | {
        attendanceMonth?: T;
        absentDates?:
          | T
          | {
              type?: T;
              date?: T;
              from?: T;
              to?: T;
              reason?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "student-progress_select".
 */
export interface StudentProgressSelect<T extends boolean = true> {
  tenant?: T;
  student?: T;
  coach?: T;
  evaluations?:
    | T
    | {
        evaluationMonth?: T;
        remarks?: T;
        evaluation?:
          | T
          | {
              skillCategory?: T;
              score?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tournaments_select".
 */
export interface TournamentsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  tournamentType?: T;
  registrationFee?: T;
  description?: T;
  registrationStartDate?: T;
  registrationEndDate?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tournament-registrations_select".
 */
export interface TournamentRegistrationsSelect<T extends boolean = true> {
  tenant?: T;
  tournament?: T;
  user?: T;
  registrationDate?: T;
  paymentStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tournament-teams_select".
 */
export interface TournamentTeamsSelect<T extends boolean = true> {
  tenant?: T;
  tournament?: T;
  teams?:
    | T
    | {
        teamName?: T;
        players?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tournament-matches_select".
 */
export interface TournamentMatchesSelect<T extends boolean = true> {
  tenant?: T;
  tournament?: T;
  matches?:
    | T
    | {
        teamOne?: T;
        teamTwo?: T;
        winner?: T;
        court?: T;
        scheduledTime?: T;
        scores?:
          | T
          | {
              teamOneScore?: T;
              teamTwoScore?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tournament-results_select".
 */
export interface TournamentResultsSelect<T extends boolean = true> {
  tenant?: T;
  tournament?: T;
  teamPositions?:
    | T
    | {
        team?: T;
        position?: T;
        prizeAmount?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "training-schedules_select".
 */
export interface TrainingSchedulesSelect<T extends boolean = true> {
  tenant?: T;
  trainingGroup?: T;
  coach?: T;
  schedules?:
    | T
    | {
        courts?: T;
        daysOfWeek?: T;
        startTime?: T;
        endTime?: T;
        id?: T;
      };
  offDays?:
    | T
    | {
        type?: T;
        date?: T;
        from?: T;
        to?: T;
        reason?: T;
        id?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "member-schedules_select".
 */
export interface MemberSchedulesSelect<T extends boolean = true> {
  tenant?: T;
  shiftName?: T;
  schedules?:
    | T
    | {
        courts?: T;
        daysOfWeek?: T;
        startTime?: T;
        endTime?: T;
        id?: T;
      };
  offDays?:
    | T
    | {
        type?: T;
        date?: T;
        from?: T;
        to?: T;
        reason?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "court-bookings_select".
 */
export interface CourtBookingsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  user?: T;
  bookings?:
    | T
    | {
        courts?: T;
        bookingDate?: T;
        startTime?: T;
        endTime?: T;
        id?: T;
      };
  confirmed?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  tenant?: T;
  userId?: T;
  channel?: T;
  type?: T;
  status?: T;
  payload?: T;
  sentAt?: T;
  readAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  tenant?: T;
  userId?: T;
  action?: T;
  collection?: T;
  documentId?: T;
  diff?: T;
  ip?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: number;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskEnforceTenantSubscriptions".
 */
export interface TaskEnforceTenantSubscriptions {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSendBillingReminders".
 */
export interface TaskSendBillingReminders {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskDispatchPendingNotifications".
 */
export interface TaskDispatchPendingNotifications {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}